-- Catálogo Dinamo compartido: modelos y esquemas de financiamiento.
-- Fuente de verdad de los datos: cotizador-pt/index.html (lista 25/08/2026).

create table public.modelos (
  id                  bigint generated by default as identity primary key,
  nombre              text not null unique,
  precio_lista        integer not null check (precio_lista > 0),
  servicio_preventivo integer not null default 0 check (servicio_preventivo >= 0),
  tipo                text,
  descripcion         text,
  imagen_url          text,
  activo              boolean not null default true,
  orden               integer not null
);
comment on table public.modelos is 'Motos de Dinamo. precio_lista es SIN servicio preventivo.';

create table public.esquemas (
  id            text primary key,
  etiqueta      text not null,
  enganche_min  numeric(5,2) not null,
  enganche_max  numeric(5,2) not null,
  unidad_plazo  text not null check (unidad_plazo in ('quincenas','semanas')),
  orden         integer not null,
  check (enganche_min <= enganche_max)
);

create table public.esquema_niveles (
  id              bigint generated by default as identity primary key,
  esquema_id      text not null references public.esquemas(id),
  enganche_desde  numeric(5,2) not null,
  enganche_hasta  numeric(5,2) not null,
  check (enganche_desde <= enganche_hasta)
);
create index esquema_niveles_esquema_idx on public.esquema_niveles (esquema_id);

create table public.multiplicadores (
  nivel_id  bigint not null references public.esquema_niveles(id) on delete cascade,
  plazo     integer not null check (plazo > 0),
  factor    numeric(9,7) not null check (factor > 0),
  primary key (nivel_id, plazo)
);

create table public.parametros (
  clave  text primary key,
  valor  text not null
);

alter table public.modelos          enable row level security;
alter table public.esquemas         enable row level security;
alter table public.esquema_niveles  enable row level security;
alter table public.multiplicadores  enable row level security;
alter table public.parametros       enable row level security;

-- Lectura pública: los cotizadores leen con la clave publicable.
-- Sin políticas de escritura: solo service_role (Table Editor, scripts) escribe.
create policy "lectura publica" on public.modelos         for select to anon, authenticated using (true);
create policy "lectura publica" on public.esquemas        for select to anon, authenticated using (true);
create policy "lectura publica" on public.esquema_niveles for select to anon, authenticated using (true);
create policy "lectura publica" on public.multiplicadores for select to anon, authenticated using (true);
create policy "lectura publica" on public.parametros      for select to anon, authenticated using (true);
